# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo verify git is intalled
    git version
    echo Add a new weview git remote service
    git remote add weview-bucket https://weview-test@bitbucket.org/weview-test/test.git
    echo Push source code to weview
    git push weview-bucket
  displayName: 'Run a multi-line script'
